### PR TITLE
mark_utf8 should set encoding to the name of lists

### PR DESCRIPTION
**Pull request by shrektan**
or when read the yaml files, the Chinese var names display messes still.

### CODE REVIEW

**Comment by jjallaire** [comment]
@yihui I'll let you review and merge this one since you are the foremost export on UTF-8!

@shrektan Could you add an item to inst/NEWS for this fix?

**Comment by shrektan** [comment]
@jjallaire added.

@yihui Actually, I find this issue when I use your code in `bookdown` for reading utf-8 yaml files...

**Comment by yihui** [comment]
@shrektan Great. Thanks a lot! Actually are you familiar with C? I really hope someone can fix the root problem in the yaml package instead of patching it over and over again.

**Comment by shrektan** [comment]
@yihui unfortunately I'm not~

**Comment by yihui** [comment]
@shrektan That is fine. I have found a C expert and will try his solution.

**Pull request merged**
