### PR TITLE
more work on toc_float

### PR DESCRIPTION
**Pull request by jjallaire**
- add support for collapsed and smooth_scroll options
- scroll to h1 when targeting first h2

### CODE REVIEW

**Comment by davidcarslaw** [comment]
This looks very useful - welcome addition for longer documents. I realise you have just added the code but when I try it it only shows level 2 section headings (i.e. ##) and not level 1 (#)...

**Comment by jjallaire** [comment]
That's correct, it shows only level 2 and below by design (Level 1 is
intended for the document title and thus doesn't get an entry in the TOC).

**Comment by davidcarslaw** [comment]
Ah, right - thanks. In that case if I have a document where the toc is true, it gives section number 0.1, 0.2 etc - which seems a bit odd, or am I missing something? Is it that the floating TOC is meant to be used without section numbers and will only show level 2 section titles?

Let me take the opportunity to thank you all for the excellent, high quality software you provide to the community. It really has changed the way people work with R for the better.

**Comment by jjallaire** [comment]
There may be something we can do about the section numbering. Could you
provide a simple example Rmd which I can work from?

**Comment by davidcarslaw** [comment]
Here's a simple example based on the Rmd default template. In this case, # is used for the title (as advised) and the top-level section is ##. Although the advice is toc_depth should be 2, I think it can be 3 and still show ok in the floating toc. My feeling is that a section numbered 1, 2, 3 etc. should be associated with a single # and 1.1, 1.2, 1.3 should be ## etc. I would consider the title to be outside the definition of sections? A toc_depth of 2 would then show 1, 1.1 etc.

I've put a gist [here](https://gist.github.com/davidcarslaw/6a5ca92ef2dc68256e81) as I couldn't work out how to embed markdown in markdown...

**Comment by jjallaire** [comment]
I see what you are saying. I tried playing with the --number-offset pandoc
arg to get something closer to what you were hoping for but that still ends
up numbering the first ## as "1.1" (rather than "1" as I think you were
hoping for). It just seems like pandoc section numbering in HTML flat out
doesn't work very well.

**Comment by davidcarslaw** [comment]
Thanks. Pandoc itself seems OK (version 1.15.0.6). Given a simple markdown document:

```
# My top-level topic

## My first subtopic

## Another subtopic

### A sub-subtopic

## Another top-level topic
```

and then compile `pandoc --number-sections < markdownTest.md > out.html`, I get:

image

which seems OK...

**Comment by jjallaire** [comment]
That's what I get as well. I think the underlying problem results from the
fact that:

1) Pandoc seems to expect that # will be used as a header within HTML
documents (they add class="title" to the document header so it can be
styled distinctly) and it's section numbering behavior is based on this
assumption.

2) In the R Markdown ecosystem we've been using ## as the standard top
level header since forever.

3) The TOC generation library we use (tocify) has a bug which breaks the
TOC if you include a header level in the "selectors" for the TOC and then
it isn't in the document the whole TOC fails to show. This is basically why
we can't just automatically include h1 in the TOC selectors.

So I think the story here just isn't very good for the time being. I'll
keep noodling on whether there is a way out of the box.

**Comment by davidcarslaw** [comment]
Great - many thanks JJ; much appreciated.

**Comment by jjallaire** [comment]
I ended up being able to fix the bug in tocify that prevented enabling h1
selectors for the table of contents. So now you can use # as a header
within your document and everything will work as expected (and you'll get
the section number behavior you want).

**Comment by davidcarslaw** [comment]
Wow - quick work! This is excellent and much appreciated. It really helps to navigate long documents - very slick and effective. I just tested it on my document and I can confirm it works as expected.

**Comment by jjallaire** [comment]
Okay, glad we figured that out!

**Pull request merged**
