### PR TITLE
Fixes #283.

### LINKED ISSUE #283: Support `opts_template`
The new `opts_template` options are not supported in the existing `knitr_options`.  These can be set in the same way the other options can be set, using `$set()` and `$get()`.

Currently any templates defined before calling `render` work as expected but it would be preferable to have explicit support.

### PR DESCRIPTION
**Pull request by jamiefolson**
Adds support for knitr option templates in the knitr options.

### CODE REVIEW

**Comment by jjallaire** [comment]
@yihui  does this look okay to you?

**Comment by yihui** [comment]
@jjallaire Yes, it does. 

@jamiefolson It will be nice if you can avoid white space changes in the future to make the patch a little cleaner. You probably also need to upgrade your roxygen2 package. Thanks!

**Comment by jjallaire** [comment]
@jamiefolson If we don't already have one could you send us a contributor agreement as described here: https://github.com/rstudio/rmarkdown/blob/master/CONTRIBUTING.md

**Comment by jamiefolson** [comment]
It looks like I'm using the current version of Roxygen2 (4.1.1).  I'm not sure where the extra whitespace in the Rd files came from.  You should have a contributor agreement from last fall.

**Pull request merged**
