### PR TITLE
Support new citeproc from Pandoc 2.11

### LINKED ISSUE #1915: Support new pandoc 2.11 --citeproc option to deal with citations
Pandoc 2.11 has been released yesterday: https://github.com/jgm/pandoc/releases/tag/2.11

Among the changes, there is a new flag to use with citations instead of the pandoc-citeproc filter. 

I believe we must do some adjustment to support this new feature when `pandoc_available("2.11")`

See the release note for details.

### PR DESCRIPTION
**Pull request by cderv**
This will close #1915

### CODE REVIEW

**Comment by jjallaire** [comment]
I don't think this full closes #1915 w/o dealing w/ the `pandoc_citeproc_convert()` function.

**Comment by cderv** [comment]
Oh yes I know. This is why this is still a draft. Not yet ready to merge. I opened this draft PR to share the work and discuss if necessary. 

I should have wrote a little something to comment further...

**Comment by jjallaire** [comment]
Okay sorry about the itchy GH comment finger....didn't see that is was marked draft!

**Comment by cderv** [comment]
@jj following your comment, https://github.com/rstudio/rmarkdown/issues/1915#issuecomment-707124030: 

The manual included in the release bundle (not yet updated on website) give the infos: 

> Note that pandoc can be used to produce such a YAML metadata section from a BibTeX, BibLaTeX, or CSL JSON bibliography:
> ```
> pandoc chem.bib -s -t markdown
> pandoc chem.json -s -t markdown
> ```
> pandoc can also be used to produce CSL JSON bibliography from BibTeX, BibLaTeX, or markdown YAML:
> ```
> pandoc chem.bib -s -t csljson
> pandoc chem.yaml -s -t csljson
> ```
> Running pandoc on a bibliography file with the --citeproc option will create a formatted bibliography in the format of your choice:
> ```
> pandoc chem.bib -s --citeproc -o chem.html
> pandoc chem.bib -s --citeproc -o chem.pdf
> ```

There are some differences between the output when converted to YAML: 
* a nocite filed is added 
* There is no more spaces between fields in the new output
* Oddly, `pandoc-citeproc` will add a `...` at the end of the yaml part. `pandoc` will add a closing `---` - that seems more correct.
* Some fields are not the same. (see _issued_ below for example)

``` r
# using this PR
# remotes::install_github("rstudio/rmarkdown#1916")
temp_bib <- tempfile(fileext = ".bib")
knitr::write_bib("bookdown", temp_bib)
#> Warning in utils::citation(..., lib.loc = lib.loc): no date field in DESCRIPTION
#> file of package 'bookdown'
#> Warning in utils::citation(..., lib.loc = lib.loc): could not determine year for
#> 'bookdown' from package DESCRIPTION file
rmarkdown::find_pandoc(cache = FALSE)
#> $version
#> [1] '2.9.2.1'
#> 
#> $dir
#> [1] "C:/Users/chris/scoop/apps/rstudio-daily/current/bin/pandoc"
rmarkdown::pandoc_citeproc_convert(temp_bib, type = "yaml")
#>  [1] "---"                                                                         
#>  [2] "references:"                                                                 
#>  [3] "- id: R-bookdown"                                                            
#>  [4] "  type: book"                                                                
#>  [5] "  author:"                                                                   
#>  [6] "  - family: Xie"                                                             
#>  [7] "    given: Yihui"                                                            
#>  [8] "  issued:"                                                                   
#>  [9] "  - year: 2020"                                                              
#> [10] "  title: 'Bookdown: Authoring books and technical documents with r markdown'"
#> [11] "  title-short: Bookdown"                                                     
#> [12] "  note: R package version 0.20.6"                                            
#> [13] "  URL: https://github.com/rstudio/bookdown"                                  
#> [14] ""                                                                            
#> [15] "- id: bookdown2016"                                                          
#> [16] "  type: book"                                                                
#> [17] "  author:"                                                                   
#> [18] "  - family: Xie"                                                             
#> [19] "    given: Yihui"                                                            
#> [20] "  issued:"                                                                   
#> [21] "  - year: 2016"                                                              
#> [22] "  title: 'Bookdown: Authoring books and technical documents with R markdown'"
#> [23] "  title-short: Bookdown"                                                     
#> [24] "  publisher: Chapman; Hall/CRC"                                              
#> [25] "  publisher-place: Boca Raton, Florida"                                      
#> [26] "  note: ISBN 978-1138700109"                                                 
#> [27] "  URL: https://github.com/rstudio/bookdown"                                  
#> [28] "..."
rmarkdown::find_pandoc(cache = FALSE, dir = "C:/Users/chris/Logiciel/pandoc/pandoc-2.11/")
#> $version
#> [1] '2.11'
#> 
#> $dir
#> [1] "C:/Users/chris/Logiciel/pandoc/pandoc-2.11/"
rmarkdown::pandoc_citeproc_convert(temp_bib, type = "yaml")
#>  [1] "---"                                                                
#>  [2] "references:"                                                        
#>  [3] "- author:"                                                          
#>  [4] "  - family: Xie"                                                    
#>  [5] "    given: Yihui"                                                   
#>  [6] "  id: R-bookdown"                                                   
#>  [7] "  issued: 2020"                                                     
#>  [8] "  note: R package version 0.20.6"                                   
#>  [9] "  title: \"Bookdown: Authoring books and technical documents with r"
#> [10] "    markdown\""                                                     
#> [11] "  title-short: Bookdown"                                            
#> [12] "  type: book"                                                       
#> [13] "  url: \"https://github.com/rstudio/bookdown\""                     
#> [14] "- author:"                                                          
#> [15] "  - family: Xie"                                                    
#> [16] "    given: Yihui"                                                   
#> [17] "  id: bookdown2016"                                                 
#> [18] "  issued: 2016"                                                     
#> [19] "  note: ISBN 978-1138700109"                                        
#> [20] "  publisher: Chapman; Hall/CRC"                                     
#> [21] "  publisher-place: Boca Raton, Florida"                             
#> [22] "  title: \"Bookdown: Authoring books and technical documents with R"
#> [23] "    markdown\""                                                     
#> [24] "  title-short: Bookdown"                                            
#> [25] "  type: book"                                                       
#> [26] "  url: \"https://github.com/rstudio/bookdown\""                     
#> [27] "---"                                                                
#> [28] ""
```

<sup>Created on 2020-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Do we need to get the output of `pandoc_citeproc_convert` to be the same no matter which pandoc version used ? 
I believe we should just provide a wrapper to make the conversion but keep the output as the pandoc binary or pandoc-citeproc binary is doing. That would mean not remove the nocite maybe. 

What do you think ?

**Comment by jjallaire** [comment]
I agree it's fine to keep the `nocite` in there until we discover there is a reason to remove it.

**Comment by jjallaire** [comment]
@cderv FYI I wanted to bump the version in DESCRIPTION so I merged `master` into `new-citeproc`.

**Comment by cderv** [comment]
That is good idea ! I forgot to bump it thanks! 

This should be ready. Pandoc 2.11+ is now tested and will not use `pandoc-citeproc` now.

**Review by jjallaire — APPROVED** [review]

**Comment by jjallaire** [comment]
@yihui Are you okay if we go ahead and merge this?

**Comment by yihui** [comment]
@jjallaire Hold on please. There seems to be something wrong with the merge commit c14b9672920ca4b8ca7d817feb742d00d99d9dad that you pushed. We lost some commits there. It might be because I deleted 3077b34dff6224150fb6ebbd6613757d3ad9a545 and 348ed780077d4ab87def075a6c0b592453fb581e from the master branch (since the latter just reverted the former). Sorry about that, but I guess we have to get rid of c14b9672920ca4b8ca7d817feb742d00d99d9dad. Are you okay with me doing that? It'll be a force push...

**Comment by jjallaire** [comment]
That’s fine, I can just add that back after. Sorry about that I had
forgotten to push that so it got stale

**Review by yihui — APPROVED** [review]
Okay. The PR looks good to me, and I'll merge it right now. Thanks!

**Comment by yihui** [comment]
@jjallaire I've restored the master branch, and you may have to clone the repo again.

**Comment by jjallaire** [comment]
Thx, yes, that took care of it!

**Comment by doronbehar** [comment]
Hey all, I'm encountering an issue with rmarkdown 2.5 which is supposed to include the change of this PR:

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.0.2  magrittr_1.5    htmltools_0.5.0 tools_4.0.2     yaml_2.2.1     
 [6] tinytex_0.27    stringi_1.4.6   rmarkdown_2.5   knitr_1.30      stringr_1.4.0  
[11] xfun_0.19       digest_0.6.25   rlang_0.4.7     evaluate_0.14
```

I get:

```
> rmarkdown::render("background.Rmd"	output_format = "pdf_document")	
processing file: background.Rmd		
|.........................................................................................| 100%		
ordinary text without R code		
output file: background.knit.md		
/usr/local/bin/pandoc +RTS -K512m -RTS background.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output background.tex --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in' --filter /usr/local/bin/pandoc-citeproc		
[WARNING] Deprecated: pandoc-citeproc filter. Use --citeproc instead.		
pandoc-citeproc: Error in $: Incompatible API versions: encoded with [1	22] but attempted to decode with [1	21].
CallStack (from HasCallStack):		
error	called at ./Text/Pandoc/JSON.hs:112:48 in pandoc-types-1.21-LpPdBV1sPudK4kVghsVxWs:Text.Pandoc.JSON	
Error running filter /usr/local/bin/pandoc-citeproc:		
Filter returned error status 1		
Error: pandoc document conversion failed with error 83
```

Where on a terminal:

```
$ /usr/local/bin/pandoc --version
pandoc 2.11.1
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,
citeproc 0.1.0.3, ipynb 0.1.0.1
User data directory: /Users/udi/.local/share/pandoc or /Users/udi/.pandoc
Copyright (C) 2006-2020 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

And if I don't install `pandoc-citeproc` (via homebrew), I get a 127 error due to `pandoc-citeproc` not found. If I _do_ install `pandoc-citeproc`, I get the rstudio error above, which is essentially this issue:

https://github.com/jgm/pandoc-citeproc/issues/448

----

So what should I do? All packages are updated to their latest, including pandoc and it's version is not detected correctly? It should be, according to the [NEWS](https://github.com/rstudio/rmarkdown/blob/master/NEWS.md#rmarkdown-25) right?

**Pull request merged**
