### PR TITLE
Mention that postscript probably should not be cropped

### PR DESCRIPTION
**Pull request by yihui**
Closes yihui/knitr#1365

### CODE REVIEW

**Comment by jjallaire** [comment]
Could we auto-disable it for the postscript graphics device?

**Comment by jjallaire** [comment]
I'll merge this then leave it to you whether and how we should do an auto-disable.

**Comment by yihui** [comment]
I thought about it before submitting the PR. The problem is I don't know whether it is always a bad idea to crop postscript figures. I can disable cropping for postscript, but it will be difficult to enable it if cropping actually works (will require a separate chunk option like `crop.eps`), so I'd rather just document it. I believe the number of people using postscript should be fairly small.

**Comment by jjallaire** [comment]
Okay, sounds good.

**Pull request merged**
