### PR TITLE
patch beamer template: restore paragraph spacing

### PR DESCRIPTION
**Pull request by kevinushey**
This resolves https://github.com/rstudio/rmarkdown/issues/744.

### CODE REVIEW

**Comment by jjallaire** [comment]
@yihui could you take a quick look and merge if it looks okay to you? (Yihui created the original version of the patch code). See https://github.com/jgm/pandoc-templates/issues/207 for details on why the additional patch is necessary.

@kevinushey Could you add a NEWS item for this?

**Comment by yihui** [comment]
Looks good. The current pandoc version in RStudio is 1.17.0.2, and I'm not sure if you really mean 1.17.2 or 1.17.0.2.

**Comment by kevinushey** [comment]
I'm using the latest version of pandoc installed with homebrew, which is currently 1.17.2, so that check is intentional.

**Comment by yihui** [comment]
Oh I just saw that. Yep, this makes perfect sense, then.

**Pull request merged**
