### PR TITLE
Add template as output_render_files of discover_rmd_resources()

### PR DESCRIPTION
**Pull request by atusy**
solves #457﻿ and #1864

Please see the discussion in #1864 for the reason of changes.

### CODE REVIEW

**Comment by cderv** [comment]
Yes this is now the good fix ! 👍  Thank you ! 

I think the source of the issue is the discovery of template as an external resource. see https://github.com/rstudio/rmarkdown/issues/1864#issuecomment-660706526
I think the NEWS should be that `rmarkdown::find_external_resources()` now discovers external template file (and this fix also the shiny runtime, and intermediate_dir set to something, because the run find_external_ressources)

Maybe we should also take the opportunity to add some tests ? Not sure if there are already some about this, and if this is easy to add.

**Comment by atusy** [comment]
@cderv 
Thanks for your insightful comments and smaller reprex!!
I'll update NEWS and consider about tests.

**Comment by atusy** [comment]
It seems difficult to unit test  `rmarkdown:::discover_rmd_resources` because it's second argument requires a complex function, which is defined internally by `find_external_resources`...
Unit testing `find_external_resources` is also difficult because it `render`s input file and requires valid resources (e.g., `reference_docx` must be a valid `docx` file).

**Comment by atusy** [comment]
A first step to unit test `discover_rmd_resources` would be to pull out `discover_single_resource` from `find_external_resources`, and unit test `discover_single_resource`.
As `discover_single_resource` requires some hyper parameters, we also have to define a function that defines `discover_single_resource`...
I think such a heavy steps should be done separate PR(s).

```r
generate_discover_single_resource <- function(input_dir, .envir = parent.frame()) {
  force(input_dir)
  force(.envir)
  discover_single_resource <- function(path, explicit, web) {

    if (!(is.character(path) && length(path) == 1 && path != "." && path != ".." &&
          file.exists(file.path(input_dir, path))))
      return(FALSE)

    ext <- tolower(tools::file_ext(file.path(input_dir, path)))

    if (identical(ext, "r")) {
      # if this is a .R script, look for resources it contains, too
      discover_r_resources(file.path(input_dir, path), discover_single_resource)
    } else if (identical(ext, "css")) {
      # if it's a CSS file, look for files it references (e.g. fonts/images)
      discover_css_resources(file.path(input_dir, path), discover_single_resource)
    }
    # if this is an implicitly discovered resource, it needs to refer to
    # a file rather than a directory
    if (!explicit && dir_exists(file.path(input_dir, path))) {
      return(FALSE)
    }

    # this looks valid; remember it
    .envir$discovered_resources <<- rbind(.envir$discovered_resources, data.frame(
      path = path, explicit = explicit, web = web, stringsAsFactors = FALSE
    ))
    TRUE
  }
  return(discover_single_resource)
}
```

**Comment by cderv** [comment]
I see. thanks for trying. I know that some steps need to be done in order to improve the "adding unit test easily" in rmarkdown. 

However, I think we can just for now add to the existing one, don't you think ?  
https://github.com/rstudio/rmarkdown/blob/ff1b279e795b62b1ffeabcc9aa5bf7386a7ebb83/tests/testthat/test-resources.R

this would require:
* create a `empty2.html`
* add `template: empty2.html` to the yaml header in https://github.com/rstudio/rmarkdown/blob/master/tests/testthat/resources/rmarkdown.Rmd

What do you think ?

**Comment by atusy** [comment]
@cderv That is a good idea, and glad to hear aboiut `test-resources.R`.
Thanks!! Will try.

My fault is that I ran `usethis::use_test()`, and found no tests in `test-html_resources.R`.

**Comment by atusy** [comment]
@cderv I don't understand why, but I face a warning and an error by updating test.

```
✓ |  OK F W S | Context
x |  13 1 24   | resource discovery 
[WARNING] Could not parse YAML metadata at line 18 column 1: :11:35: Unexpected '
  '

test-resources.R:20: failure: R Markdown resource discovery finds expected resources
`resources` not equal to `expected`.
Attributes: < Component “row.names”: Numeric: lengths (6, 9) differ >
Component “path”: Lengths (6, 9) differ (string compare on first 6)
Component “path”: 6 string mismatches
Component “explicit”: Lengths (6, 9) differ (comparison on first 6 components)
Component “explicit”: 1 element mismatch
Component “web”: Lengths (6, 9) differ (comparison on first 6 components)
Component “web”: 3 element mismatches
```

If I print `resources` and `expected`, they are I see some missing files in `resources`.

```r
> resource
         path explicit   web
6   empty.csv    FALSE FALSE
1    empty.md    FALSE FALSE
2   empty.png    FALSE FALSE
5   empty.Rmd    FALSE FALSE
4   empty.tsv     TRUE FALSE
3 empty2.html    FALSE FALSE

> expected
         path explicit   web
5   empty.css    FALSE  TRUE
9   empty.csv    FALSE FALSE
7  empty.html    FALSE  TRUE
6   empty.jpg    FALSE  TRUE
1    empty.md    FALSE FALSE
2   empty.png    FALSE FALSE
4   empty.Rmd    FALSE FALSE
3   empty.tsv     TRUE FALSE
8 empty2.html    FALSE  TRUE
```

**Comment by cderv** [comment]
This is indeed tricky.
In fact `discover_rmd_resources` will run `discover_html_resources` that will render the Rmd document to html. And as an empty template is provided, some resources previously found in the resulting html are not found now. (Like the css file)

This template argument is a tricky one.

**Comment by atusy** [comment]
I see thanks. I'll copy default template instead.

**Comment by atusy** [comment]
GREAT!! WE PASSED TESTS!!

Huge thanks to @cderv!!

**Review by yihui — APPROVED** [review]
The discussions seem lengthy to me so I didn't read them very carefully, but the change seems to be simple enough (essentially one line of change), so I'll just trust you two and merge this PR. Thanks a lot!

**Pull request merged**
