### PR TITLE
set.seed(100) for default_site

### PR DESCRIPTION
**Pull request by jjallaire**
In the websites we've created with rmarkdown to date we've included set.seed(100) in the website Makefile to ensure that html output doesn't constantly churn based on the random number seed (this ends up creating much messier and hard to reason about diffs).

We also include that in our rmarkdown-webstie example: https://github.com/rstudio/rmarkdown-website/blob/master/Makefile#L9

Is there any reason we can think of not to do this here?

### CODE REVIEW

**Comment by jjallaire** [comment]
@yihui @hadley

**Comment by yihui** [comment]
I think this is fine.

**Comment by hadley** [comment]
Hmmm, I'd worry a little about making it so hidden - it's going to be surprising if you're doing simulations. Could it at least be a parameter so it's documented and possible to turn off?

**Comment by jjallaire** [comment]
Or I wonder if a better way of doing this in general is via .Rprofile
rather than in the Makefile or site generator? Would it work just as well
to do it in .Rprofile?

**Comment by hadley** [comment]
Yeah, I think that makes more sense.

**Comment by yihui** [comment]
I said it was fine because I thought very few people would actually end up using `default_site()` at all. For a whole website, I think the vast majority of users will customize the site generator. I'm okay if `set.seed()` is either included in `default_site()` or not.

**Comment by jjallaire** [comment]
Okay, I'm going to close this PR (I do think default_site will be used frequently for simple 4 or 5 page websites based on html_document).

**Pull request closed without merging**
