### PR TITLE
Add `$pkgVersion` to shiny prerendered dependencies

### PR DESCRIPTION
**Pull request by gadenbuie**
This is a temporary fix for #2217 to add the `$pkgVersion` string to the dependencies recorded in shiny prerendered Rmds. The reprex is the same as the one provided by @aronatkins:

Given the following `server.Rmd` and `server.R`:

````
---
title: "server.Rmd: rendered at most once"
runtime: shinyrmd
---

This document can be slow for the first client. The R code block is evaluated
at render-time, which occurs at most once, and only when the HTML does not
already exist. When the HTML already exists, there is no render cost.

```{r}
Sys.sleep(1)
```
````

```r
# server.R that pairs with server.Rmd.
function(input, output) {}
```

Run this document, stop the server, then check if we see a pre-render as still necessary.

```r
# This call to run() will render "server.html" and then start a Shiny server.
# Stop the Shiny server once it starts listening.
rmarkdown::run(file = "./server.Rmd")

# Check to see if a pre-render is still needed:
rmarkdown:::shiny_prerendered_prerender("./server.Rmd", "./server.html", ".", "1")
# => FALSE

# Perform another call to run(); this will run another render of "server.html"
# before starting the Shiny server.
rmarkdown::run(file = "./server.Rmd")
# => starts without re-render
```

### CODE REVIEW

**Comment by cderv** [comment]
If this is temporary fix only, I just want to check: 
@aronatkins as you have a workaround, is this interesting to you in the short term ?

**Comment by gadenbuie** [comment]
> If this is temporary fix only, 

@cderv just to clarify, I think the change is valid and needed to make the current implementation consistent, but temporary in the sense that we should revisit and improve the entire implementation in the (near?) future.

**Comment by cderv** [comment]
Oh ok ! Thanks for the clarification ! 

In that case, I'll have a look on monday (with fresh mind) in order to merge quickly this. Thank you for your help on this ! Much appreciated!

**Comment by aronatkins** [comment]
@cderv I found #2217 while trying to understand the behavior of `rmarkdown::run` against "normal" Shiny R Markdown documents versus pre-rendered Shiny R Markdown documents. My work will handle the rendering outside of `run()` (and will likely force `RMARKDOWN_RUN_PRERENDER=0`; I have no urgency for this fix.

**Review by cderv — APPROVED** [review]
Thanks @gadenbuie and sorry for the delay on this one. 

At least, I took time to understand and this is now clearer to me. We should definitely update the HTML dependencies handling based on recent **htmltools**.

**Pull request merged**
