### PR TITLE
Render each file in site in a fresh R process

### PR DESCRIPTION
**Pull request by jennybc**
I have a (legacy) R Markdown website: <https://jennybc.github.io/purrr-tutorial/>

I'm having difficulty building the site with `rmarkdown::render_site()` because the search path is leaked from file to file and, therefore, undesirable and hard-to-control function masking is happening, even though each individual *file* has the correct `library()` calls. Each individual file can be rendered with no problems.

In another context, I would use explicit name spacing to solve this, but that's not so great in a pedagogical setting. Also, it just doesn't seem right that, by the time you render file 50, your search path reflects every `library()` call in files 1 - 49.

Is there any way this would be accepted? I'd be happy to refine.

### CODE REVIEW

**Comment by jennybc** [comment]
I'm surprised tests pass with my first commit. They fail for me locally like so:

```
✖ |  6 1     | site [1.1 s]
─────────────────────────────────────────────────────────
test-site.R:54: failure: render_site does not leak search path across files
any(grepl("stringr", b, fixed = TRUE)) isn't false.
─────────────────────────────────────────────────────────
```

Is there any chance `skip_on_cran()` is somehow active on travis?

**Comment by gaborcsardi** [comment]
Some extra motivation: in the near future we'll be able to render the files in parallel, in a bunch of worker processes.

**Comment by jennybc** [comment]
OK let's move forward.

Any suggestions re: the name or key in `_site.yml` to request rendering each file in a separate, fresh process, i.e. `SOMETHING` below? Is there an existing term we should honour? Sounds like we should also keep the prospect of parallel execution in mind.

```
name: "my-website"
output_dir: "_site"
include: ["import.R"]
exclude: ["docs.txt", "*.csv"]
SOMETHING: true
```

Also, my current PR suppresses the usual output from the rendering. We just get the spinner provided by callr, which is probably too minimal. What do we want re: progress reporting?

**Comment by yihui** [comment]
Oh naming. That's the hardest part. In bookdown, I used `new_session`: https://bookdown.org/yihui/bookdown/new-session.html Not sure if that is a good name.

`new_session` can be `true`, `false`, or `parallel` (again, not sure if this is a good idea--blending logical values with string values in the same option).

I don't have an opinion on progress reporting. Perhaps we can do that after someone files a feature request.

**Comment by gaborcsardi** [comment]
I can help with progress reporting, it is actually easy, we can just get the output of the remote process, and print it to the screen.

**Comment by gaborcsardi** [comment]
So the output goes like this:
```r
callr::r(
  function() { for  (i in 1:5) { print(i); Sys.sleep(1) } }, 
  block_callback = function(x) cat(x)
)
```

**Comment by jennybc** [comment]
OK the new behaviour is triggered if and only if `new_session: true` is found in `_site.yml`. callr is moved to Suggests.

How is this looking @yihui?

Not yet handled:

  * Documentation
  * Progress reporting

**Comment by jennybc** [comment]
This doesn't seem right but ... is the `.Rd` file for this hand-edited? Once that's clarified, I will find a place to mention the `new_session` configuration approach in the docs.

@yihui I think the implementation and test is ready for another look.

**Comment by jdblischak** [comment]
I super support this PR. Please see this old issue for another motivating use case: #1326

**Comment by jennybc** [comment]
I have it on good authority that yes this `.Rd` file is maintained by hand. I will make a separate PR to convert it to roxygen and then, once that is merged, merge master into this PR, to keep things separate.

**Comment by jennybc** [comment]
Thanks @yihui!

The more I think about this, the more I think maybe `rmarkdown::render() itself should offer a `new_session` argument. So that it's easy for mere mortals to do with `rmarkdown::render()` what they do when they click the "Knit" button in RStudio. But that is a bigger change and something I would leave to the maintainers. But obviously, if that ever happened, then this PR could be undone and the `new_session: true` config would simply get wired up to that fictional argument.

**Pull request merged**
