### PR TITLE
Add ability to set 'opts_hooks' in knitr_options()

### PR DESCRIPTION
**Pull request by aoles**
Addresses issue https://github.com/rstudio/rmarkdown/issues/672.

### CODE REVIEW

**Comment by yihui** [comment]
Looks perfect to me. Had you brought this PR in the first place, there'd be no question asked in #672 :)

The only caveat is that this would require knitr >= 1.12, which I think is fine.

**Comment by aoles** [comment]
Thanks @yihui , I didn't explain properly my intentions and the actual problem in https://github.com/rstudio/rmarkdown/issues/672 in first place either, so no worries! :) I also didn't expect that the fix would be so easy, as I assumed that there were some reasons not to include `opts_hooks` in `knitr_options`; but after looking into the code the solution seemed to be evident.

**Comment by jjallaire** [comment]
Looks good! A couple of small additions to request:

1) Let's update the knitr version dependency to 1.12

2) Let's add an item to NEWS

**Comment by aoles** [comment]
Thank you @jjallaire! I've made the requested updates.

I've already sent the Contributor Agreement to my previous PR last year (https://github.com/rstudio/rmarkdown/pull/569). My contact details didn't change since then. Do I need to sign a fresh copy or are you fine with the old one?

**Comment by yihui** [comment]
The old copy of the agreement should be fine.

**Pull request merged**
