### PR TITLE
add support to page through paged tables

### PR DESCRIPTION
**Pull request by javierluraschi**
Same UI for paged tables; however, clicking on the "..." column will page through all columns. Support to change number of visible columns based on available space.

### CODE REVIEW

**Comment by jjallaire** [comment]
What's the UI affordance for paging back and forward (I get the "..." but how do you then page back?).

**Comment by javierluraschi** [comment]
@jjallaire Yes, for sure:

screen shot 2016-08-04 at 7 49 20 am
screen shot 2016-08-04 at 7 49 27 am
screen shot 2016-08-04 at 7 49 33 am

**Comment by jjallaire** [comment]
Maybe an arrow/triangle instead?

**Comment by javierluraschi** [comment]
Yes, updated:

screen shot 2016-08-04 at 9 26 51 am

screen shot 2016-08-04 at 9 27 00 am

**Pull request merged**
