### PR TITLE
Add Ubuntu 20.04 to the test matrix

### PR DESCRIPTION
**Pull request by jeroen**
To reproduce https://github.com/rstudio/rmarkdown/issues/2099

### CODE REVIEW

**Comment by cderv** [comment]
Thanks for this PR showing the issue.

I added Pandoc 2.5 in the config matrix. 

Is Ubuntu 20.04 problematic ? Should we switch from 18.04 to 20.04 ?

**Comment by cderv** [comment]
Build is still failing in r-universe, so I'll test it too

**Comment by cderv** [comment]
Oh no My mistake, it is working. it was just a sync issue between Github actions and r-universe page.

**Comment by jeroen** [comment]
Yes it seems fixed, thanks

**Pull request closed without merging**
