### PR TITLE
feat(beamer): support latex_dependencies

### LINKED ISSUE #2478: `beamer_presentation` does not resolve latex_dependencies
````markdown
---
output: 
  pdf_document:
    keep_tex: true
    keep_md: true
---

```{r}
knitr::asis_output("", meta = list(rmarkdown::latex_dependency("longtable")))
```

\begin{longtable}{r|r}
\hline
speed & dist\\
\hline
4 & 2\\
\end{longtable}

````

This will throw: 
````
output file: test.knit.md

! LaTeX Error: Environment longtable undefined.
````

`pdf_document` does not. This is because we don't resolve depdencies in `beamer_presentation` format. 

`extra_dependencies` is not even allowed argument

Initially from https://community.rstudio.com/t/apparent-bug-in-rmarkdown-to-beamer-using-gt/164778

### PR DESCRIPTION
**Pull request by atusy**
closes #2478

Confirmed it works by the following script.

```r
writeLines(
  c(
    '```{r}',
    'knitr::asis_output("", meta = list(rmarkdown::latex_dependency("longtable")))',
    '```',
    '\\begin{longtable}{r|r} \\hline speed & dist\\\\ \\hline 4 & 2\\\\ \\end{longtable}'
  ),
  "example.Rmd"
)

render("example.Rmd", beamer_presentation())
```

### CODE REVIEW

**Review by yihui — APPROVED** [review]
Looks good to me. Thanks!

**Review by cderv — COMMENTED** [review]
Awesome thank you ! 

If possible it would be great to add some test. 

Thanks!

**Comment by atusy** [comment]
@cderv 
Thanks for the suggestion. I added test cases for `pre_processor`s of `pdf_document` and `beamer_presentation`.

**Review by cderv — APPROVED** [review]
Thanks a lot ! 

Also for improving the testing - long overdue switch to version 3 thank you !

**Pull request merged**
