### PR TITLE
feat: individually select folding when code_folding: hide

### LINKED ISSUE #664: feature_request: code_folding for a specific chunk
I'm using a lot rmarkdown to construct labs for my student. I've seen the new code_folding option and I was wondering if this option could be specified/modified for some specific chunks. I'm considering using this option so that some hints/solutions are invisible until the students request them.
Thanks,
Erwan

### PR DESCRIPTION
**Pull request by atusy**
This PR enables code_folding for a specific chunk and closes #664.

This works by hiding all source codes as default except for sources that have 'fold-show' class.

- specifying `code_folding: hide` in YAML front matter
- specifying `class.source='fold-show'`

````
---
output:
  html_document:
    code_folding: hide
---

```{r class.source = 'fold-show'}
1
```

```{r class.source = 'fold-show'}
2
```

```{r}
# This source is hidden
```
````

If anyone wants to default to show all and hide specific ones, try

````
---
output:
  html_document:
    code_folding: hide
---

```{r}
knitr::opts_chunk$set(class.source='fold-show')
```

```{r}
'Shown by default'
```

```{r class.source = NULL}
'Hidden manually'
```
````

Maybe we can consider more for better class name?

### CODE REVIEW

**Comment by atusy** [comment]
Thank you for approving!

**Comment by StoyoKaramihalev** [comment]
Thanks for making this happen! It would be quite useful to have a way to do the opposite too. That is, if code is shown by default to only hide a specific chunk, perhaps using a "fold-hide"? For data pipeline demo notebooks it's always nice to make the important code and plots visible, but I'd like to hide the code for making the plots.

**Comment by yihui** [comment]
I agree that will be useful, too. Another PR please? :)

**Comment by atusy** [comment]
Here you are!!
https://github.com/rstudio/rmarkdown/pull/1798

**Comment by StoyoKaramihalev** [comment]
That’s great, thanks so much! :)

**Comment by yihui** [comment]
Thanks @atusy! And @StoyoKaramihalev You can install the development version via:

```r
remotes::install_github('rstudio/rmarkdown')
```

**Pull request merged**
